#!/usr/bin/env bash

VERSION=0.2.0

#set -e

FLUTTER_APP_HOME="$(pwd -P)"
FLUTTERW_CACHE_DIR="$FLUTTER_APP_HOME/.flutterw/cache/wrapper"

function addToGitignore() {
  if [[ -e "${FLUTTER_APP_HOME}/.gitignore" && $(grep -c ".flutterw/cache/" "${FLUTTER_APP_HOME}"/.gitignore) -eq '0' ]]; then
    echo "" >> "${FLUTTER_APP_HOME}"/.gitignore
    echo ".flutterw/cache/" >>"${FLUTTER_APP_HOME}"/.gitignore
  fi
}

function toMd5() {
  if builtin command -v md5 >/dev/null; then
    echo "$1" | md5
  elif builtin command -v md5sum >/dev/null; then
    echo "$1" | md5sum | awk '{print $1}'
  else
    echo "Neither md5 nor md5sum were found in the PATH"
    return 0
  fi
  return 1
}

#NOW=`date '+%Y-%m-%d'`

## Flutterw-Dev-Mode
NOW=$(date '+%Y-%m-%d(%H:%M:%s)')

FLUTTERW_CACHE_FILE="${FLUTTERW_CACHE_DIR}/$(toMd5 "${NOW}")"

if [[ ! -e ${FLUTTERW_CACHE_FILE} ]]; then
  rm -rf "${FLUTTERW_CACHE_DIR}"
  addToGitignore
#  curl -s --create-dirs -H "Cache-Control: no-cache" "file:///${FLUTTER_APP_HOME}/wrapper/flutter-wrapper" -o "${FLUTTERW_CACHE_FILE}"
  curl -s --create-dirs -H "Cache-Control: no-cache" "http://tosv.byted.org/obj/ttclient-android/flutter-wrapper" -o "${FLUTTERW_CACHE_FILE}"
fi

bash "${FLUTTERW_CACHE_FILE}" "$@"
